version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Nepal
    volumes:
      - ./config:/config
      - ~/backups/media/Movies/:/movies 
      - ~/backups/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped