version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Nepal
    volumes:
      - ./config:/config
      # - /path/to/tvseries:/tv #optional
      - ../../backups/download:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped