---
version: "2"
services:
  homer:
 
    image: b4bz/homer
    container_name: homer
    volumes:
      - .:/www/assets
    restart: unless-stopped
    ports:
      - 80:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
